### ISSUE TITLE
__dirname is not defined

### ISSUE THREAD

**Issue by cravler** [ModuleLoader/node-es-module-loader#10]
Given this snippet:

```js
import util from 'util';
console.log(__dirname);
```

the result when trying to load this module is:

```bash
console.log(__dirname);
            ^
__dirname is not defined
```

Same thing with `__filename`

**Comment by guybedford** [comment]
Yes `__filename` and `__dirname` are CommonJS and node-specific constructs. We support `__moduleName` currently for this, although it will be changing to `import.meta.url` soon as per https://github.com/tc39/proposal-import-meta.
