### ISSUE TITLE
Adding stack trace. 

### ISSUE THREAD

**Issue by chyzwar** [ModuleLoader/node-es-module-loader#2]
Hi, 

ModuleLoader is great project and I am really excited. You are guys a liberators of babel.
Can you add longer stack traces or include orginalErr. I added console log in line 14 before throw.

It is difficult to see deduct anything from:

```
    throw err;
    ^

Cannot read property 'method' of undefined
```

**Comment by guybedford** [comment]
Thanks for trying it out. Can you share the reproduction of this case at all?

This may just be a matter of an update as this has been worked on quite carefully in https://github.com/ModuleLoader/es-module-loader/blob/master/test/3-register-loader.js#L185.

**Comment by chyzwar** [comment]
myResponse.js

```
import http from 'http';

class myResponse extends http.ServerResponse{
  constructor(){
    super();
  }
}

export default myResponse;
```

test.js

```
import myResponse from 'myResponse';

new myResponse();
```

Error is coming from the the lack of req being passed in super.
Problem I had is that original stack trace was hidden and name of module was misleading.

**Comment by guybedford** [comment]
Thanks for the update, sure I've added a fix for this in https://github.com/ModuleLoader/es-module-loader/commit/86a9c16104bb93c33437fab69c0de22308b907d2 and pushed out a release.
