### ISSUE TITLE
node --inspect debugging - source maps

### ISSUE THREAD

**Issue by dmonad** [ModuleLoader/node-es-module-loader#3]
You mention the new `node --inspect` feature for debugging. Unfortunately, I can't step through the original code. Instead I have to step through the transpiled code. Is this the expected behavior, or is this a problem with the source maps? 

![screenshot from 2016-08-22 00-06-41](https://cloud.githubusercontent.com/assets/5553757/17840101/06e3eab0-67fd-11e6-9dd0-31775e056d32.png)

~~ Ubuntu 16.04, Node 6.4, stable chrome, reproducible on any source

**Comment by guybedford** [comment]
Yes while the source maps show up in the debugger, stepping through the original source doesn't seem to be supported at the moment. Although if you add a debugger in the original source it seems to find the right spot in the transpiled source. So I think it's all working correctly, but just a limitation of the debugger.

**Comment by dmonad** [comment]
Got it, thanks! I'll close this issue because it really is a node issue. There was already a feature request nodejs/node#7087
