### ISSUE TITLE
loader.import do not work with relative imports.

### ISSUE THREAD

**Issue by chyzwar** [ModuleLoader/node-es-module-loader#4]
Example:

//test1.js

```
const test = 'super';
export default test;
```

//test2.js

```
const promise = loader.import('./test1').then((test)=> {
  console.log(test);
})
```

**Comment by guybedford** [comment]
Yes, the global import is not contextual.

We provide a non-standard `__moduleName` global for this case:

``` javascript
loader.import('./test1', __moduleName).then(test => console.log(test));
```

We will implement the proposed specification for:

``` javascript
import('./test1').then(test => console.log(test))
```

as soon as that is confirmed at the coming TC39 meeting and we can get support in Babel.

**Comment by chyzwar** [comment]
It is possible to load import in sync way?

**Comment by guybedford** [comment]
No this is not supported by the new loader.
