### ISSUE TITLE
problems finding modules

### ISSUE THREAD

**Issue by rootsical** [ModuleLoader/node-es-module-loader#5]
hi. i am trying to find a way to use 'import'/'export' es module syntax in node, instead of 'require' and commonjs. i am hoping this is what this project was created for.

i am having a problem getting it to work though. the problem may be the same as [issue #4](https://github.com/ModuleLoader/node-es-module-loader/issues/4) but i didn't understand the solution.

my initial javascript entry point, init.js:

``` javascript
//init.js
var NodeESModuleLoader = require('node-es-module-loader');
var loader = new NodeESModuleLoader(); 
loader.import('./main.js').then(function() {
  // ...
  console.log('loaded!');
});
```

which is attempting to load main.js

``` javascript
// main.js
// "format es6"; // may be required as we are not 'exporting' anything?
import * as hello from './hello.js';
hello.welcome('Jimmy');
```

which, in turn, is attempting to load hello.js

``` javascript
// hello.js
export function welcome(name) {
    console.log('Welcome, ' + name + '!!!!');
};
```

code is run using:
`node init.js`

i have installed node-es-module-loader v0.1.8. no other packages are installed.

my project root is:
`D:\DEV\JS\modules-in-node`

i am getting this error:

```
Error: Cannot find module 'D:/DEV/JS/main.js'
Loading ./main.js
```

if i try:

``` javascript
var loader = new NodeESModuleLoader("D:/DEV/JS/modules-in-node/"); 
// passing the absolute path to project root
```

i get this error:

```
Error: Cannot find module 'hello.js'
Resolving ./hello.js to D:\DEV\JS\modules-in-node\main.js
Loading D:\DEV\JS\modules-in-node\main.js
Loading ./main.js
```

all js scripts are placed directly in the project root. i am on windows 8.1 x64 and using node v6.6.0.

thanks for any help you might be able to provide..

**Comment by guybedford** [comment]
Thanks, yes this was a bug. I've released the fix in the latest version.
