### ISSUE TITLE
debug, inspect node flags

### ISSUE THREAD

**Issue by chyzwar** [ModuleLoader/node-es-module-loader#6]
I would like to use new --inspect flag in node. 

Module loader use shebang but maybe child_process can be used to start new node process with desired flags?

**Comment by guybedford** [comment]
Did you try the `node --inspect node_modules/.bin/node-esml module.js` approach here?

**Comment by chyzwar** [comment]
nope, thank you for pointing this.

I mostly using node-esml executable. 
`node-esml module.js`

**Comment by guybedford** [comment]
Great. If you think other flags would be useful here do ask.
