### ISSUE TITLE
_asyncToGenerator is not a function

### ISSUE THREAD

**Issue by shellscape** [ModuleLoader/node-es-module-loader#8]
Node 7.6

Given this snippet:

```js
async function load () {
  for (let method of Object.keys(routes)) {
    let pairs = routes[method];

    for (let name of Object.keys(pairs)) {
      let path = pairs[name],
        route = await import(`./routes/${name}`);

      router[method](path, route);
    }
  }
}

load();
```

the following error is thrown when run using `node-esml`:

```
_asyncToGenerator is not a function
  Evaluating /.../lib/router.js
  Evaluating /.../lib/app.js
  Loading /.../lib/app
  TypeError: _asyncToGenerator is not a function
    at eval (/.../lib/router.js!transpiled:31:20)
    at Object.execute (/.../lib/router.js!transpiled:164:8)
    at declarativeExecute (/.../node_modules/node-es-module-loader/dist/node-es-module-loader.js:1158:15)
    at doEvaluate (/.../node_modules/node-es-module-loader/dist/node-es-module-loader.js:1087:15)
    at doEvaluate (/.../node_modules/node-es-module-loader/dist/node-es-module-loader.js:1074:19)
    at ensureEvaluate (/.../node_modules/node-es-module-loader/dist/node-es-module-loader.js:1020:15)
    at /.../node_modules/node-es-module-loader/dist/node-es-module-loader.js:621:16
```

`async/await` is available natively in node 7.6, so I'm not sure why this is attempting to convert at all.

**Comment by guybedford** [comment]
Thanks for posting. Await should work though. Do you have a local `.babelrc` file? If so it might be trying to apply that.

**Comment by shellscape** [comment]
Ah, I do in fact have a `.babelrc` file; we're using babel for vue.js code that needs transpiling. What's the workaround in that case?

**Comment by guybedford** [comment]
We could potentially add a commandline argument to control the babelrc option and null it out. Otherwise run node-esml from a folder lower than the folder with the babelrc file.

**Comment by shellscape** [comment]
OK. I'm not sure that's going to work for our setup, but I could rename the babel config and instruct babel to use it. Should we close this issue or leave it open for reference to the potential option you mentioned?

**Comment by guybedford** [comment]
I'd like to keep this project minimalistic, so let's close for now rather.
